### ISSUE TITLE
Sungrow -->SH10RT+SBR128 Battery+AC011E-01 Wallbox evcc->mqtt(localhost) failed

### ISSUE THREAD

**Issue by btota** [Hoellenwesen/home-assistant-configurations#1]
Hey, glad to hear that, my constellation: Sungrow -->SH10RT+SBR128 Battery+AC011E-01 Wallbox

everything is working fine with mkaiser (thanksalot) and modbus-proxy addon on hassos; except the Sungrow AC011E-01 wb. I don´t have a clue, which sensors to use, so I installed on hassos ModbusTCP2MQTT, Mosquitto broker to get more registers recognized. Both addons are working fine, but I don´t get the registers/sensors from the AC011E Wallbox. On isolarcloud the AC011E-01 is shown up the right way.

In evcc addon unfortunately I'm not able to use the modbus-proxy (localhost:502), so I tried your automation.yaml and evcc.yaml plus Mosquitto broker `Using config file: /config/evcc.yaml starting evcc: 'EVCC_DATABASE_DSN=/data/evcc.db evcc --config /config/evcc.yaml' [main  ] INFO 2023/07/01 18:29:38 evcc 0.118.2 [main  ] INFO 2023/07/01 18:29:38 using config file: /config/evcc.yaml [main  ] INFO 2023/07/01 18:29:38 starting ui and api at :7070 [mqtt  ] INFO 2023/07/01 18:29:38 connecting evcc-1293083007 at tcp://localhost:1883 [main  ] FATAL 2023/07/01 18:29:38 failed configuring mqtt: error connecting: network Error : dial tcp [::1]:1883: connect: connection refused [main  ] FATAL 2023/07/01 18:29:38 will attempt restart in: 5m0s` with issues?

**Comment by Hoellenwesen** [comment]
Hi,

do you use the Home Assistant Mosquitto broker Addon? I have exposed the port 1883 in the Mosquitto addon config and use my IP address of Home Assistant instead of "localhost". If you are using the addon you could also try to use "core-mosquitto:1883" as broker address in EVCC.

With the tool MQTT Explorer (http://mqtt-explorer.com/) you could then also check if HA is publishing the data correctly into the MQTT broker.

Unfortunately i do not own a AC011E-01 Wallbox. Currently i'm trying to integrate my Heidelberg Wallbox.

**Comment by markus023** [comment]
FYI Just installed mkaiser modbus integration (SH6.0RT / SBR096) using local LAN-Port. Everything is working.
Now installed HA-evcc add-on using the mqtt export automation on local HA-mosquito Addon.
evcc is starting and getting all pv data from HA mqtt.

@Hoellenwesen just a short reply that your automation is generally working , thanks for your work/sharing 👍 

I haven't tried to use evcc ( got a Wallbox Pulsar with OCPP ) , but basically everything shows up on evcc.

**Comment by btota** [comment]
> Hi,
> 
> do you use the Home Assistant Mosquitto broker Addon? I have exposed the port 1883 in the Mosquitto addon config and use my IP address of Home Assistant instead of "localhost". If you are using the addon you could also try to use "core-mosquitto:1883" as broker address in EVCC.
> 
> With the tool MQTT Explorer (http://mqtt-explorer.com/) you could then also check if HA is publishing the data correctly into the MQTT broker.
> 
> Unfortunately i do not own a AC011E-01 Wallbox. Currently i'm trying to integrate my Heidelberg Wallbox.

Hey - I hope you made it :), I'm still struggling with starting evcc (*evcc protocol-->missing loadpoints?). 
modbus-proxy-->modbustcpmqtt-->mosquito-->your pvdataevcc addon--> seems to work (*mqtt-explorer)
 
![Bildschirmfoto vom 2023-07-21 18-57-01](https://github.com/Hoellenwesen/home-assistant-configurations/assets/71133306/571c2297-2866-42b2-aa7c-b00dcd76d854)
![Bildschirmfoto vom 2023-07-21 19-00-13](https://github.com/Hoellenwesen/home-assistant-configurations/assets/71133306/a588fd25-c4b2-49e1-a10a-6ca5b6475db2)
![Bildschirmfoto vom 2023-07-21 19-00-42](https://github.com/Hoellenwesen/home-assistant-configurations/assets/71133306/ed5a69b3-4caf-4ca0-ab47-8222a7f2e5da)

**automations.yaml**
`alias: PV Daten zu EVCC via MQTT
description: ""
trigger:
  - platform: time_pattern
    seconds: /5
condition: []
action:
  - service: mqtt.publish
    data:
      topic: pvdataevcc/grid/power
      payload_template: " {{ states('sensor.export_power_raw') }} "
  - service: mqtt.publish
    data:
      topic: pvdataevcc/grid/imported
      payload_template: " {{ states('sensor.total_imported_energy') }} "
  - service: mqtt.publish
    data:
      topic: pvdataevcc/pv/power
      payload_template: " {{ states('sensor.total_dc_power') }} "
  - service: mqtt.publish
    data:
      topic: pvdataevcc/pv/energy
      payload_template: " {{ states('sensor.total_pv_generation') }} "
  - service: mqtt.publish
    data:
      topic: pvdataevcc/pv/current/l1
      payload_template: " {{ states('sensor.phase_a_current') }} "
  - service: mqtt.publish
    data:
      topic: pvdataevcc/pv/current/l2
      payload_template: " {{ states('sensor.phase_b_current') }} "
  - service: mqtt.publish
    data:
      topic: pvdataevcc/pv/current/l3
      payload_template: " {{ states('sensor.phase_c_current') }} "
  - service: mqtt.publish
    data:
      topic: pvdataevcc/battery/power
      payload_template: " {{ states('sensor.signed_battery_power') }} "
  - service: mqtt.publish
    data:
      topic: pvdataevcc/battery/energy
      payload_template: " {{ states('sensor.total_battery_discharge') }} "
  - service: mqtt.publish
    data:
      topic: pvdataevcc/battery/level
      payload_template: " {{ states('sensor.battery_level') }} "
mode: single
`

**evcc.yaml**
`meters:
  - name: grid
    type: custom
    power:
      source: mqtt
      topic: pvdataevcc/grid/power
      scale: -1
    energy:
      source: mqtt
      topic: pvdataevcc/grid/imported

  - name: pv
    type: custom
    power:
      source: mqtt
      topic: pvdataevcc/pv/power
    energy:
      source: mqtt
      topic: pvdataevcc/pv/energy
    currents:
      - source: mqtt
        topic: pvdataevcc/pv/current/l1
      - source: mqtt
        topic: pvdataevcc/pv/current/l2
      - source: mqtt
        topic: pvdataevcc/pv/current/l3

  - name: battery
    type: custom
    power:
      source: mqtt
      topic: pvdataevcc/battery/power
      scale: -1
    energy:
      source: mqtt
      topic: pvdataevcc/battery/energy
    soc:
      source: mqtt
      topic: pvdataevcc/battery/level

site:
  title: Home # display name for UI
  meters:
    grid: grid # grid meter
    pv:
      - pv # list of pv inverters/ meters
    battery:
      - battery # list of battery meters
  residualPower: 100 # additional household usage margin

mqtt:
  broker: 192.168.178.43:1883 #
  user: yyy
  password: xxx`

![Bildschirmfoto vom 2023-07-21 19-19-43](https://github.com/Hoellenwesen/home-assistant-configurations/assets/71133306/65c7886e-5032-43d8-80a1-8c617abae070)

**Comment by Hoellenwesen** [comment]
Hi,
according to your error message i think you are missing the configuration for a loadpoint in your evcc.yaml. You need to configure all required sections in your config file. e.g. https://docs.evcc.io/docs/reference/configuration/loadpoints/
