### ISSUE TITLE
payload_template Deprecate 2025.2.0

### ISSUE THREAD

**Issue by fwittenfeld** [Hoellenwesen/home-assistant-configurations#2]
THX for sharing your config.
Since my last HA update, I get a warning, that your Code stops working from HA 2025.2.0.
See: https://github.com/home-assistant/core/pull/122098

**Comment by Hoellenwesen** [comment]
Hi,
yes thanks, i'm already aware of that and i will fix it soon. Currently there is no functional issue, just the warning.

**Comment by Hoellenwesen** [comment]
Fixed
